sudo: false
# addons:
#  apt:
#    packages:
#      - oracle-java9-installer

language: java
install: true
jdk:
#- openjdk8
- oraclejdk10

env:
  matrix:
  - TERM=dumb

before_install:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start

before_script:
  - ./gradlew --version
  
script:
    - TERM=dumb ./gradlew clean build -S #-x :vworkflows-demo:jfxJar

after_success:
  - TERM=dumb ./gradlew test jacocoTestReport jacocoRootReport coveralls -S
